Support variable array indexing for header stacks
usha1830/p4c pull request #24
Opened 2022-05-25 05:59 UTC by usha1830

This PR is to support variable array indexing for accessing the elements of a header stack using subscript notation.
The array index expression within the following statements/expressions are supported

- Assignment statements (on both sides as well)
- Table keys
- If condition
- Switch expression
- Function param
- Binary operation
- Unary Operation
- Slice

`meta.left = hdrs.udp[meta.depth - 1].sport;`

should be translated as 

```
tmp = meta.depth - 1
if (tmp == 0)
    meta.left = hdrs.udp[0].sport;
if (tmp == 1)
    meta.left = hdrs.udp[1].sport;
```

If the array subscript is present on both sides with different expression in the [], it will be translated into multi level branches like below:

`hdrs.udp[meta.depth].sport = hdrs.udp[meta.depth - 1].sport;`  =>

```
tmp = meta.depth - 1
tmp1 = meta.depth

if (tmp1 == 0)
    if (tmp == 0)
        hdr.udp[0].sport = hdr.udp[0].sport
if (tmp == 1)
        hdr.udp[0].sport = hdr.udp[1].sport
if (tmp1 == 1)
    if (tmp == 0)
        hdr.udp[1].sport = hdr.udp[0].sport
if (tmp == 1)
        hdr.udp[1].sport = hdr.udp[1].sport		
```

2022-05-27 09:14 UTC, psivanup requested changes
Please check the comments.

2022-05-27 09:14 UTC, psivanup commented on backends/dpdk/dpdkArch.cpp
> +        return false;
any specific reason to have tmp variable? root shall be used.

2022-05-27 09:14 UTC, psivanup commented on backends/dpdk/dpdkArch.cpp
> +        ai = mem->expr->to<IR::ArrayIndex>();
not indented properly, a blank also there.

2022-05-27 09:14 UTC, psivanup commented on backends/dpdk/dpdkArch.cpp
> +        if (ai->left->is<IR::Member>())
ai shall be nullptr if 'mem->expr->type->is<IR::Type_Stack>()' is false.

2022-05-27 09:23 UTC, usha1830 commented on backends/dpdk/dpdkArch.cpp
> +        return false;
It caused some issue. I am trying to recollect why I introduced tmp here :(

2022-05-27 10:38 UTC, usha1830 commented on backends/dpdk/dpdkArch.cpp
> +        return false;
In this pass, root is not PathExpression type, it is of type IR::Expression. directly assigning with new path expression throws build error.

2022-05-27 11:02 UTC, psivanup commented on backends/dpdk/dpdkArch.cpp
> +        return false;
Ok

2022-05-27 13:55 UTC, usha1830 commented on backends/dpdk/dpdkArch.cpp
> +        if (ai->left->is<IR::Member>())
Updated to move the hasHSE check from Assignment statement visitor to replaceVarIndexWithIf function. This makes sure the pointers are not null.
Please check.

2022-05-27 14:22 UTC, psivanup approved these changes
Looks ok to me, there are optional comments though.

2022-05-27 14:22 UTC, psivanup commented on backends/dpdk/dpdkArch.cpp
> +                 complex = true;
can add an early break here.

2022-05-30 05:22 UTC, github-sajan approved these changes
Code looks fine to me

2022-05-30 05:22 UTC, github-sajan commented on backends/dpdk/dpdkArch.cpp
> +    if (sf->type->is<IR::Type_Stack>()){
cpplint error ? space missing before curly braces

2022-05-30 05:23 UTC, kamleshbhalui approved these changes

2022-05-30 05:30 UTC, usha1830 commented on backends/dpdk/dpdkArch.cpp
> +    if (sf->type->is<IR::Type_Stack>()){
Will update

2022-05-30 05:55 UTC, psivanup approved these changes
The changes look fine to me.

2022-06-02 03:09 UTC, closed without merging